services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tech_passwd}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - fiaptechchallengenetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tech" ]
      interval: 5s
      timeout: 5s
      retries: 10

  fiapfastfood:
    container_name: fiap-fast-food
    build:
      context: .
    image: fiap/fastfoodgrupo10
    ports:
      - "8080:8080"
    networks:
      - fiaptechchallengenetwork
    depends_on:
      postgres:
        condition: service_healthy

networks:
  fiaptechchallengenetwork:
    name: fiaptechchallengenetwork
    driver: bridge