spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
  jpa:
    show-sql: true


mercadopago:
  access_token: ${MP_ACCESS_TOKEN:TEST-2194493215547460-072323-e7020fc0d11389fdae3dc86c6b9a1e4f-115466963}
  notification_url: ${MP_NOTIFICATION_URL:https://webhook.site/820da4fd-08cc-446d-8f0d-d4b9f22738b9/pagamentos/pedidos/notifications}
