apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-application
  labels:
    app: tech-fiap-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-fiap-application
  template:
    metadata:
      labels:
        app: tech-fiap-application
    spec:
      containers:
        - name: tech-fiap-api-container
          image: gabriwl/tech-fiap:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: cm-api
          ports:
            - containerPort: 80
